global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wordpress'
    static_configs:
      - targets: ['wordpress:9720'] # WordPress container
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80'] # NGINX container
